[package]
name = "tredis"
version = "0.1.0"
edition = "2021"

[dependencies]
bytes = "1.3.0"                                     # helps manage buffers
thiserror = "1.0.32"                                # error handling
tokio = { version = "1.23.0", features = ["full"] } # async networking
chrono = "0.4.39"
regex = "1.11.1"
